<div class="row map-wrapper">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-6">
                <input class="form-control" id="search">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div id="map"></div>
            </div>
            <div class="col-sm-6">
                <ul class="list-group" id="places">
                </ul>
            </div>

        </div>

    </div>

</div>
