<html>
    <head>
        <title>TravelPlanner</title>
        <script src="<?php echo $this->host; ?>asset/mootools.js"></script>
        <script src="<?php echo $this->host; ?>js/main/"></script>

        <link rel="stylesheet" href="<?php echo $this->host; ?>asset/bootstrap.css">
        <link rel="stylesheet" href="<?php echo $this->host; ?>asset/style.css">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <?php echo $this->render('menu.phtml'); ?>
            </div>

            <?php echo $this->render($this->template); ?>
        </div>


        <script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->config['api_key']; ?>&libraries=places&callback=initMap" async defer></script>
    </body>
</html>
